// ============================================================
// FIFA WORLD CUP 2026 -- MATCH DATA
// ============================================================
// Live tournament data as of July 1, 2026 (mid Round of 32).
// This is the file to edit as later rounds get real teams and scores.
//
// Fields:
//   home / away        -- team name. Flags are looked up automatically
//                         in flags.js by matching this name exactly.
//   homeScore/awayScore -- final score as numbers, or null if not played/decided
//   date                -- YYYY-MM-DD
//   venue               -- stadium / city
//   note                -- optional extra info shown after the score (e.g. penalty shootout)
//
// Knockout matches not yet decided use placeholders like
// "Winner Match 93" -- replace these with the real team name once
// the earlier match finishes. No flag will show for a placeholder
// until you do (that is expected).
//
// Do NOT change "id" once you have started checking off matches.
// ============================================================

const WORLD_CUP_MATCHES = [

  // ---------------- GROUP STAGE ----------------
  // Group A
  {
    id: "m1",
    matchNumber: 1,
    stage: "Group Stage",
    group: "Group A",
    round: "Matchday 1",
    date: "2026-06-11",
    venue: "Estadio Azteca, Mexico City",
    home: "Mexico",
    away: "South Africa",
    homeScore: 2,
    awayScore: 0,
    note: null
  },
  {
    id: "m2",
    matchNumber: 2,
    stage: "Group Stage",
    group: "Group A",
    round: "Matchday 1",
    date: "2026-06-11",
    venue: "TBD",
    home: "South Korea",
    away: "Czechia",
    homeScore: 2,
    awayScore: 1,
    note: null
  },
  {
    id: "m3",
    matchNumber: 3,
    stage: "Group Stage",
    group: "Group A",
    round: "Matchday 2",
    date: "2026-06-18",
    venue: "TBD",
    home: "Czechia",
    away: "South Africa",
    homeScore: 1,
    awayScore: 1,
    note: null
  },
  {
    id: "m4",
    matchNumber: 4,
    stage: "Group Stage",
    group: "Group A",
    round: "Matchday 2",
    date: "2026-06-18",
    venue: "TBD",
    home: "Mexico",
    away: "South Korea",
    homeScore: 1,
    awayScore: 0,
    note: null
  },
  {
    id: "m5",
    matchNumber: 5,
    stage: "Group Stage",
    group: "Group A",
    round: "Matchday 3",
    date: "2026-06-24",
    venue: "TBD",
    home: "Czechia",
    away: "Mexico",
    homeScore: 0,
    awayScore: 3,
    note: null
  },
  {
    id: "m6",
    matchNumber: 6,
    stage: "Group Stage",
    group: "Group A",
    round: "Matchday 3",
    date: "2026-06-24",
    venue: "TBD",
    home: "South Africa",
    away: "South Korea",
    homeScore: 1,
    awayScore: 0,
    note: null
  },
  // Group B
  {
    id: "m7",
    matchNumber: 7,
    stage: "Group Stage",
    group: "Group B",
    round: "Matchday 1",
    date: "2026-06-12",
    venue: "TBD",
    home: "Canada",
    away: "Bosnia and Herzegovina",
    homeScore: 1,
    awayScore: 1,
    note: null
  },
  {
    id: "m8",
    matchNumber: 8,
    stage: "Group Stage",
    group: "Group B",
    round: "Matchday 1",
    date: "2026-06-13",
    venue: "TBD",
    home: "Qatar",
    away: "Switzerland",
    homeScore: 1,
    awayScore: 1,
    note: null
  },
  {
    id: "m9",
    matchNumber: 9,
    stage: "Group Stage",
    group: "Group B",
    round: "Matchday 2",
    date: "2026-06-18",
    venue: "TBD",
    home: "Switzerland",
    away: "Bosnia and Herzegovina",
    homeScore: 4,
    awayScore: 1,
    note: null
  },
  {
    id: "m10",
    matchNumber: 10,
    stage: "Group Stage",
    group: "Group B",
    round: "Matchday 2",
    date: "2026-06-18",
    venue: "TBD",
    home: "Canada",
    away: "Qatar",
    homeScore: 6,
    awayScore: 0,
    note: null
  },
  {
    id: "m11",
    matchNumber: 11,
    stage: "Group Stage",
    group: "Group B",
    round: "Matchday 3",
    date: "2026-06-24",
    venue: "TBD",
    home: "Switzerland",
    away: "Canada",
    homeScore: 2,
    awayScore: 1,
    note: null
  },
  {
    id: "m12",
    matchNumber: 12,
    stage: "Group Stage",
    group: "Group B",
    round: "Matchday 3",
    date: "2026-06-24",
    venue: "TBD",
    home: "Bosnia and Herzegovina",
    away: "Qatar",
    homeScore: 3,
    awayScore: 1,
    note: null
  },
  // Group C
  {
    id: "m13",
    matchNumber: 13,
    stage: "Group Stage",
    group: "Group C",
    round: "Matchday 1",
    date: "2026-06-13",
    venue: "TBD",
    home: "Brazil",
    away: "Morocco",
    homeScore: 1,
    awayScore: 1,
    note: null
  },
  {
    id: "m14",
    matchNumber: 14,
    stage: "Group Stage",
    group: "Group C",
    round: "Matchday 1",
    date: "2026-06-13",
    venue: "TBD",
    home: "Haiti",
    away: "Scotland",
    homeScore: 0,
    awayScore: 1,
    note: null
  },
  {
    id: "m15",
    matchNumber: 15,
    stage: "Group Stage",
    group: "Group C",
    round: "Matchday 2",
    date: "2026-06-19",
    venue: "TBD",
    home: "Scotland",
    away: "Morocco",
    homeScore: 0,
    awayScore: 1,
    note: null
  },
  {
    id: "m16",
    matchNumber: 16,
    stage: "Group Stage",
    group: "Group C",
    round: "Matchday 2",
    date: "2026-06-19",
    venue: "TBD",
    home: "Brazil",
    away: "Haiti",
    homeScore: 3,
    awayScore: 0,
    note: null
  },
  {
    id: "m17",
    matchNumber: 17,
    stage: "Group Stage",
    group: "Group C",
    round: "Matchday 3",
    date: "2026-06-24",
    venue: "TBD",
    home: "Scotland",
    away: "Brazil",
    homeScore: 0,
    awayScore: 3,
    note: null
  },
  {
    id: "m18",
    matchNumber: 18,
    stage: "Group Stage",
    group: "Group C",
    round: "Matchday 3",
    date: "2026-06-24",
    venue: "TBD",
    home: "Morocco",
    away: "Haiti",
    homeScore: 4,
    awayScore: 2,
    note: null
  },
  // Group D
  {
    id: "m19",
    matchNumber: 19,
    stage: "Group Stage",
    group: "Group D",
    round: "Matchday 1",
    date: "2026-06-12",
    venue: "TBD",
    home: "USA",
    away: "Paraguay",
    homeScore: 4,
    awayScore: 1,
    note: null
  },
  {
    id: "m20",
    matchNumber: 20,
    stage: "Group Stage",
    group: "Group D",
    round: "Matchday 1",
    date: "2026-06-13",
    venue: "TBD",
    home: "Australia",
    away: "Turkiye",
    homeScore: 2,
    awayScore: 0,
    note: null
  },
  {
    id: "m21",
    matchNumber: 21,
    stage: "Group Stage",
    group: "Group D",
    round: "Matchday 2",
    date: "2026-06-19",
    venue: "TBD",
    home: "USA",
    away: "Australia",
    homeScore: 2,
    awayScore: 0,
    note: null
  },
  {
    id: "m22",
    matchNumber: 22,
    stage: "Group Stage",
    group: "Group D",
    round: "Matchday 2",
    date: "2026-06-19",
    venue: "TBD",
    home: "Turkiye",
    away: "Paraguay",
    homeScore: 0,
    awayScore: 1,
    note: null
  },
  {
    id: "m23",
    matchNumber: 23,
    stage: "Group Stage",
    group: "Group D",
    round: "Matchday 3",
    date: "2026-06-25",
    venue: "TBD",
    home: "Turkiye",
    away: "USA",
    homeScore: 3,
    awayScore: 2,
    note: null
  },
  {
    id: "m24",
    matchNumber: 24,
    stage: "Group Stage",
    group: "Group D",
    round: "Matchday 3",
    date: "2026-06-25",
    venue: "TBD",
    home: "Paraguay",
    away: "Australia",
    homeScore: 0,
    awayScore: 0,
    note: null
  },
  // Group E
  {
    id: "m25",
    matchNumber: 25,
    stage: "Group Stage",
    group: "Group E",
    round: "Matchday 1",
    date: "2026-06-14",
    venue: "TBD",
    home: "Germany",
    away: "Curacao",
    homeScore: 7,
    awayScore: 1,
    note: null
  },
  {
    id: "m26",
    matchNumber: 26,
    stage: "Group Stage",
    group: "Group E",
    round: "Matchday 1",
    date: "2026-06-14",
    venue: "TBD",
    home: "Ivory Coast",
    away: "Ecuador",
    homeScore: 1,
    awayScore: 0,
    note: null
  },
  {
    id: "m27",
    matchNumber: 27,
    stage: "Group Stage",
    group: "Group E",
    round: "Matchday 2",
    date: "2026-06-20",
    venue: "TBD",
    home: "Germany",
    away: "Ivory Coast",
    homeScore: 2,
    awayScore: 1,
    note: null
  },
  {
    id: "m28",
    matchNumber: 28,
    stage: "Group Stage",
    group: "Group E",
    round: "Matchday 2",
    date: "2026-06-20",
    venue: "TBD",
    home: "Ecuador",
    away: "Curacao",
    homeScore: 0,
    awayScore: 0,
    note: null
  },
  {
    id: "m29",
    matchNumber: 29,
    stage: "Group Stage",
    group: "Group E",
    round: "Matchday 3",
    date: "2026-06-25",
    venue: "TBD",
    home: "Ecuador",
    away: "Germany",
    homeScore: 2,
    awayScore: 1,
    note: null
  },
  {
    id: "m30",
    matchNumber: 30,
    stage: "Group Stage",
    group: "Group E",
    round: "Matchday 3",
    date: "2026-06-25",
    venue: "TBD",
    home: "Curacao",
    away: "Ivory Coast",
    homeScore: 0,
    awayScore: 2,
    note: null
  },
  // Group F
  {
    id: "m31",
    matchNumber: 31,
    stage: "Group Stage",
    group: "Group F",
    round: "Matchday 1",
    date: "2026-06-14",
    venue: "TBD",
    home: "Netherlands",
    away: "Japan",
    homeScore: 2,
    awayScore: 2,
    note: null
  },
  {
    id: "m32",
    matchNumber: 32,
    stage: "Group Stage",
    group: "Group F",
    round: "Matchday 1",
    date: "2026-06-14",
    venue: "TBD",
    home: "Sweden",
    away: "Tunisia",
    homeScore: 5,
    awayScore: 1,
    note: null
  },
  {
    id: "m33",
    matchNumber: 33,
    stage: "Group Stage",
    group: "Group F",
    round: "Matchday 2",
    date: "2026-06-20",
    venue: "TBD",
    home: "Netherlands",
    away: "Sweden",
    homeScore: 5,
    awayScore: 1,
    note: null
  },
  {
    id: "m34",
    matchNumber: 34,
    stage: "Group Stage",
    group: "Group F",
    round: "Matchday 2",
    date: "2026-06-20",
    venue: "TBD",
    home: "Tunisia",
    away: "Japan",
    homeScore: 0,
    awayScore: 4,
    note: null
  },
  {
    id: "m35",
    matchNumber: 35,
    stage: "Group Stage",
    group: "Group F",
    round: "Matchday 3",
    date: "2026-06-25",
    venue: "TBD",
    home: "Japan",
    away: "Sweden",
    homeScore: 1,
    awayScore: 1,
    note: null
  },
  {
    id: "m36",
    matchNumber: 36,
    stage: "Group Stage",
    group: "Group F",
    round: "Matchday 3",
    date: "2026-06-25",
    venue: "TBD",
    home: "Tunisia",
    away: "Netherlands",
    homeScore: 1,
    awayScore: 3,
    note: null
  },
  // Group G
  {
    id: "m37",
    matchNumber: 37,
    stage: "Group Stage",
    group: "Group G",
    round: "Matchday 1",
    date: "2026-06-15",
    venue: "TBD",
    home: "Iran",
    away: "New Zealand",
    homeScore: 2,
    awayScore: 2,
    note: null
  },
  {
    id: "m38",
    matchNumber: 38,
    stage: "Group Stage",
    group: "Group G",
    round: "Matchday 1",
    date: "2026-06-15",
    venue: "TBD",
    home: "Belgium",
    away: "Egypt",
    homeScore: 1,
    awayScore: 1,
    note: null
  },
  {
    id: "m39",
    matchNumber: 39,
    stage: "Group Stage",
    group: "Group G",
    round: "Matchday 2",
    date: "2026-06-21",
    venue: "TBD",
    home: "Belgium",
    away: "Iran",
    homeScore: 0,
    awayScore: 0,
    note: null
  },
  {
    id: "m40",
    matchNumber: 40,
    stage: "Group Stage",
    group: "Group G",
    round: "Matchday 2",
    date: "2026-06-21",
    venue: "TBD",
    home: "New Zealand",
    away: "Egypt",
    homeScore: 1,
    awayScore: 3,
    note: null
  },
  {
    id: "m41",
    matchNumber: 41,
    stage: "Group Stage",
    group: "Group G",
    round: "Matchday 3",
    date: "2026-06-26",
    venue: "TBD",
    home: "Egypt",
    away: "Iran",
    homeScore: 1,
    awayScore: 1,
    note: null
  },
  {
    id: "m42",
    matchNumber: 42,
    stage: "Group Stage",
    group: "Group G",
    round: "Matchday 3",
    date: "2026-06-26",
    venue: "TBD",
    home: "New Zealand",
    away: "Belgium",
    homeScore: 1,
    awayScore: 5,
    note: null
  },
  // Group H
  {
    id: "m43",
    matchNumber: 43,
    stage: "Group Stage",
    group: "Group H",
    round: "Matchday 1",
    date: "2026-06-15",
    venue: "TBD",
    home: "Spain",
    away: "Cape Verde",
    homeScore: 0,
    awayScore: 0,
    note: null
  },
  {
    id: "m44",
    matchNumber: 44,
    stage: "Group Stage",
    group: "Group H",
    round: "Matchday 1",
    date: "2026-06-15",
    venue: "TBD",
    home: "Saudi Arabia",
    away: "Uruguay",
    homeScore: 1,
    awayScore: 1,
    note: null
  },
  {
    id: "m45",
    matchNumber: 45,
    stage: "Group Stage",
    group: "Group H",
    round: "Matchday 2",
    date: "2026-06-21",
    venue: "TBD",
    home: "Spain",
    away: "Saudi Arabia",
    homeScore: 4,
    awayScore: 0,
    note: null
  },
  {
    id: "m46",
    matchNumber: 46,
    stage: "Group Stage",
    group: "Group H",
    round: "Matchday 2",
    date: "2026-06-21",
    venue: "TBD",
    home: "Uruguay",
    away: "Cape Verde",
    homeScore: 2,
    awayScore: 2,
    note: null
  },
  {
    id: "m47",
    matchNumber: 47,
    stage: "Group Stage",
    group: "Group H",
    round: "Matchday 3",
    date: "2026-06-26",
    venue: "TBD",
    home: "Cape Verde",
    away: "Saudi Arabia",
    homeScore: 0,
    awayScore: 0,
    note: null
  },
  {
    id: "m48",
    matchNumber: 48,
    stage: "Group Stage",
    group: "Group H",
    round: "Matchday 3",
    date: "2026-06-26",
    venue: "TBD",
    home: "Uruguay",
    away: "Spain",
    homeScore: 0,
    awayScore: 1,
    note: null
  },
  // Group I
  {
    id: "m49",
    matchNumber: 49,
    stage: "Group Stage",
    group: "Group I",
    round: "Matchday 1",
    date: "2026-06-16",
    venue: "TBD",
    home: "France",
    away: "Senegal",
    homeScore: 3,
    awayScore: 1,
    note: null
  },
  {
    id: "m50",
    matchNumber: 50,
    stage: "Group Stage",
    group: "Group I",
    round: "Matchday 1",
    date: "2026-06-16",
    venue: "TBD",
    home: "Iraq",
    away: "Norway",
    homeScore: 1,
    awayScore: 4,
    note: null
  },
  {
    id: "m51",
    matchNumber: 51,
    stage: "Group Stage",
    group: "Group I",
    round: "Matchday 2",
    date: "2026-06-22",
    venue: "TBD",
    home: "France",
    away: "Iraq",
    homeScore: 3,
    awayScore: 0,
    note: null
  },
  {
    id: "m52",
    matchNumber: 52,
    stage: "Group Stage",
    group: "Group I",
    round: "Matchday 2",
    date: "2026-06-22",
    venue: "TBD",
    home: "Norway",
    away: "Senegal",
    homeScore: 3,
    awayScore: 2,
    note: null
  },
  {
    id: "m53",
    matchNumber: 53,
    stage: "Group Stage",
    group: "Group I",
    round: "Matchday 3",
    date: "2026-06-26",
    venue: "TBD",
    home: "Norway",
    away: "France",
    homeScore: 1,
    awayScore: 4,
    note: null
  },
  {
    id: "m54",
    matchNumber: 54,
    stage: "Group Stage",
    group: "Group I",
    round: "Matchday 3",
    date: "2026-06-26",
    venue: "TBD",
    home: "Senegal",
    away: "Iraq",
    homeScore: 5,
    awayScore: 0,
    note: null
  },
  // Group J
  {
    id: "m55",
    matchNumber: 55,
    stage: "Group Stage",
    group: "Group J",
    round: "Matchday 1",
    date: "2026-06-16",
    venue: "TBD",
    home: "Argentina",
    away: "Algeria",
    homeScore: 3,
    awayScore: 0,
    note: null
  },
  {
    id: "m56",
    matchNumber: 56,
    stage: "Group Stage",
    group: "Group J",
    round: "Matchday 1",
    date: "2026-06-17",
    venue: "TBD",
    home: "Austria",
    away: "Jordan",
    homeScore: 3,
    awayScore: 1,
    note: null
  },
  {
    id: "m57",
    matchNumber: 57,
    stage: "Group Stage",
    group: "Group J",
    round: "Matchday 2",
    date: "2026-06-22",
    venue: "TBD",
    home: "Argentina",
    away: "Austria",
    homeScore: 2,
    awayScore: 0,
    note: null
  },
  {
    id: "m58",
    matchNumber: 58,
    stage: "Group Stage",
    group: "Group J",
    round: "Matchday 2",
    date: "2026-06-22",
    venue: "TBD",
    home: "Jordan",
    away: "Algeria",
    homeScore: 1,
    awayScore: 2,
    note: null
  },
  {
    id: "m59",
    matchNumber: 59,
    stage: "Group Stage",
    group: "Group J",
    round: "Matchday 3",
    date: "2026-06-27",
    venue: "TBD",
    home: "Algeria",
    away: "Austria",
    homeScore: 3,
    awayScore: 3,
    note: null
  },
  {
    id: "m60",
    matchNumber: 60,
    stage: "Group Stage",
    group: "Group J",
    round: "Matchday 3",
    date: "2026-06-27",
    venue: "TBD",
    home: "Jordan",
    away: "Argentina",
    homeScore: 1,
    awayScore: 3,
    note: null
  },
  // Group K
  {
    id: "m61",
    matchNumber: 61,
    stage: "Group Stage",
    group: "Group K",
    round: "Matchday 1",
    date: "2026-06-17",
    venue: "TBD",
    home: "Portugal",
    away: "DR Congo",
    homeScore: 1,
    awayScore: 1,
    note: null
  },
  {
    id: "m62",
    matchNumber: 62,
    stage: "Group Stage",
    group: "Group K",
    round: "Matchday 1",
    date: "2026-06-17",
    venue: "TBD",
    home: "Uzbekistan",
    away: "Colombia",
    homeScore: 1,
    awayScore: 3,
    note: null
  },
  {
    id: "m63",
    matchNumber: 63,
    stage: "Group Stage",
    group: "Group K",
    round: "Matchday 2",
    date: "2026-06-23",
    venue: "TBD",
    home: "Portugal",
    away: "Uzbekistan",
    homeScore: 5,
    awayScore: 0,
    note: null
  },
  {
    id: "m64",
    matchNumber: 64,
    stage: "Group Stage",
    group: "Group K",
    round: "Matchday 2",
    date: "2026-06-23",
    venue: "TBD",
    home: "Colombia",
    away: "DR Congo",
    homeScore: 1,
    awayScore: 0,
    note: null
  },
  {
    id: "m65",
    matchNumber: 65,
    stage: "Group Stage",
    group: "Group K",
    round: "Matchday 3",
    date: "2026-06-27",
    venue: "TBD",
    home: "Colombia",
    away: "Portugal",
    homeScore: 0,
    awayScore: 0,
    note: null
  },
  {
    id: "m66",
    matchNumber: 66,
    stage: "Group Stage",
    group: "Group K",
    round: "Matchday 3",
    date: "2026-06-27",
    venue: "TBD",
    home: "DR Congo",
    away: "Uzbekistan",
    homeScore: 3,
    awayScore: 1,
    note: null
  },
  // Group L
  {
    id: "m67",
    matchNumber: 67,
    stage: "Group Stage",
    group: "Group L",
    round: "Matchday 1",
    date: "2026-06-17",
    venue: "TBD",
    home: "England",
    away: "Croatia",
    homeScore: 4,
    awayScore: 2,
    note: null
  },
  {
    id: "m68",
    matchNumber: 68,
    stage: "Group Stage",
    group: "Group L",
    round: "Matchday 1",
    date: "2026-06-17",
    venue: "TBD",
    home: "Ghana",
    away: "Panama",
    homeScore: 1,
    awayScore: 0,
    note: null
  },
  {
    id: "m69",
    matchNumber: 69,
    stage: "Group Stage",
    group: "Group L",
    round: "Matchday 2",
    date: "2026-06-23",
    venue: "TBD",
    home: "England",
    away: "Ghana",
    homeScore: 0,
    awayScore: 0,
    note: null
  },
  {
    id: "m70",
    matchNumber: 70,
    stage: "Group Stage",
    group: "Group L",
    round: "Matchday 2",
    date: "2026-06-23",
    venue: "TBD",
    home: "Panama",
    away: "Croatia",
    homeScore: 0,
    awayScore: 1,
    note: null
  },
  {
    id: "m71",
    matchNumber: 71,
    stage: "Group Stage",
    group: "Group L",
    round: "Matchday 3",
    date: "2026-06-27",
    venue: "TBD",
    home: "Panama",
    away: "England",
    homeScore: 0,
    awayScore: 2,
    note: null
  },
  {
    id: "m72",
    matchNumber: 72,
    stage: "Group Stage",
    group: "Group L",
    round: "Matchday 3",
    date: "2026-06-27",
    venue: "TBD",
    home: "Croatia",
    away: "Ghana",
    homeScore: 2,
    awayScore: 1,
    note: null
  },

  // ---------------- ROUND OF 32 ----------------
  {
    id: "m73",
    matchNumber: 73,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-06-28",
    venue: "SoFi Stadium, Inglewood, California",
    home: "South Africa",
    away: "Canada",
    homeScore: 0,
    awayScore: 1,
    note: null
  },
  {
    id: "m74",
    matchNumber: 74,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-06-29",
    venue: "Gillette Stadium, Foxborough, Massachusetts",
    home: "Germany",
    away: "Paraguay",
    homeScore: 1,
    awayScore: 1,
    note: "Paraguay won 4-3 on penalties"
  },
  {
    id: "m75",
    matchNumber: 75,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-06-29",
    venue: "Estadio BBVA, Monterrey, Mexico",
    home: "Netherlands",
    away: "Morocco",
    homeScore: 1,
    awayScore: 1,
    note: "Morocco won 3-2 on penalties"
  },
  {
    id: "m76",
    matchNumber: 76,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-06-29",
    venue: "NRG Stadium, Houston",
    home: "Brazil",
    away: "Japan",
    homeScore: 2,
    awayScore: 1,
    note: null
  },
  {
    id: "m77",
    matchNumber: 77,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-06-30",
    venue: "MetLife Stadium, East Rutherford, New Jersey",
    home: "France",
    away: "Sweden",
    homeScore: 3,
    awayScore: 0,
    note: null
  },
  {
    id: "m78",
    matchNumber: 78,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-06-30",
    venue: "AT&T Stadium, Arlington, Texas",
    home: "Ivory Coast",
    away: "Norway",
    homeScore: 1,
    awayScore: 2,
    note: null
  },
  {
    id: "m79",
    matchNumber: 79,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-06-30",
    venue: "Estadio Azteca, Mexico City",
    home: "Mexico",
    away: "Ecuador",
    homeScore: 2,
    awayScore: 0,
    note: null
  },
  {
    id: "m80",
    matchNumber: 80,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-07-01",
    venue: "Mercedes-Benz Stadium, Atlanta",
    home: "England",
    away: "DR Congo",
    homeScore: 2,
    awayScore: 1,
    note: null
  },
  {
    id: "m81",
    matchNumber: 81,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-07-01",
    venue: "Levi's Stadium, Santa Clara, California",
    home: "USA",
    away: "Bosnia and Herzegovina",
    homeScore: 2,
    awayScore: 0,
    note: null
  },
  {
    id: "m82",
    matchNumber: 82,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-07-01",
    venue: "Lumen Field, Seattle",
    home: "Belgium",
    away: "Senegal",
    homeScore: 3,
    awayScore: 2,
    note: null
  },
  {
    id: "m83",
    matchNumber: 83,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-07-02",
    venue: "BMO Field, Toronto",
    home: "Portugal",
    away: "Croatia",
    homeScore: 2,
    awayScore: 1,
    note: null
  },
  {
    id: "m84",
    matchNumber: 84,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-07-02",
    venue: "SoFi Stadium, Inglewood, California",
    home: "Spain",
    away: "Austria",
    homeScore: 3,
    awayScore: 0,
    note: null
  },
  {
    id: "m85",
    matchNumber: 85,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-07-02",
    venue: "BC Place, Vancouver",
    home: "Switzerland",
    away: "Algeria",
    homeScore: 2,
    awayScore: 0,
    note: null
  },
  {
    id: "m86",
    matchNumber: 86,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-07-03",
    venue: "AT&T Stadium, Arlington, Texas",
    home: "Australia",
    away: "Egypt",
    homeScore: 1,
    awayScore: 1,
    note: "Egypt won 4-2 on penalties"
  },
  {
    id: "m87",
    matchNumber: 87,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-07-03",
    venue: "Hard Rock Stadium, Miami Gardens",
    home: "Argentina",
    away: "Cape Verde",
    homeScore: 3,
    awayScore: 2,
    note: null
  },
  {
    id: "m88",
    matchNumber: 88,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-07-03",
    venue: "Arrowhead Stadium, Kansas City",
    home: "Colombia",
    away: "Ghana",
    homeScore: 1,
    awayScore: 0,
    note: null
  },

  // ---------------- ROUND OF 16 ----------------
  {
    id: "m89",
    matchNumber: 89,
    stage: "Round of 16",
    group: null,
    round: "Round of 16",
    date: "2026-07-04",
    venue: "Lincoln Financial Field, Philadelphia",
    home: "Paraguay",
    away: "France",
    homeScore: 0,
    awayScore: 1,
    note: null
  },
  {
    id: "m90",
    matchNumber: 90,
    stage: "Round of 16",
    group: null,
    round: "Round of 16",
    date: "2026-07-04",
    venue: "NRG Stadium, Houston",
    home: "Canada",
    away: "Morocco",
    homeScore: 0,
    awayScore: 3,
    note: null
  },
  {
    id: "m91",
    matchNumber: 91,
    stage: "Round of 16",
    group: null,
    round: "Round of 16",
    date: "2026-07-05",
    venue: "MetLife Stadium, East Rutherford, New Jersey",
    home: "Brazil",
    away: "Norway",
    homeScore: 1,
    awayScore: 2,
    note: null
  },
  {
    id: "m92",
    matchNumber: 92,
    stage: "Round of 16",
    group: null,
    round: "Round of 16",
    date: "2026-07-05",
    venue: "Estadio Azteca, Mexico City",
    home: "Mexico",
    away: "England",
    homeScore: 2,
    awayScore: 3,
    note: null
  },
  {
    id: "m93",
    matchNumber: 93,
    stage: "Round of 16",
    group: null,
    round: "Round of 16",
    date: "2026-07-06",
    venue: "AT&T Stadium, Arlington, Texas",
    home: "Portugal",
    away: "Spain",
    homeScore: 0,
    awayScore: 1,
    note: null
  },
  {
    id: "m94",
    matchNumber: 94,
    stage: "Round of 16",
    group: null,
    round: "Round of 16",
    date: "2026-07-06",
    venue: "Lumen Field, Seattle",
    home: "USA",
    away: "Belgium",
    homeScore: 1,
    awayScore: 4,
    note: null
  },
  {
    id: "m95",
    matchNumber: 95,
    stage: "Round of 16",
    group: null,
    round: "Round of 16",
    date: "2026-07-07",
    venue: "Mercedes-Benz Stadium, Atlanta",
    home: "Argentina",
    away: "Egypt",
    homeScore: 3,
    awayScore: 2,
    note: null
  },
  {
    id: "m96",
    matchNumber: 96,
    stage: "Round of 16",
    group: null,
    round: "Round of 16",
    date: "2026-07-07",
    venue: "BC Place, Vancouver",
    home: "Switzerland",
    away: "Colombia",
    homeScore: 0,
    awayScore: 0,
    note: "Switzerland won 4-3 on penalties"
  },

  // ---------------- QUARTERFINAL ----------------
  {
    id: "m97",
    matchNumber: 97,
    stage: "Quarterfinal",
    group: null,
    round: "Quarterfinal",
    date: "2026-07-09",
    venue: "Gillette Stadium, Foxborough, Massachusetts",
    home: "France",
    away: "Morocco",
    homeScore: 2,
    awayScore: 0,
    note: null
  },
  {
    id: "m98",
    matchNumber: 98,
    stage: "Quarterfinal",
    group: null,
    round: "Quarterfinal",
    date: "2026-07-10",
    venue: "SoFi Stadium, Inglewood, California",
    home: "Spain",
    away: "Belgium",
    homeScore: 2,
    awayScore: 1,
    note: null
  },
  {
    id: "m99",
    matchNumber: 99,
    stage: "Quarterfinal",
    group: null,
    round: "Quarterfinal",
    date: "2026-07-11",
    venue: "Hard Rock Stadium, Miami Gardens",
    home: "Norway",
    away: "England",
    homeScore: 1,
    awayScore: 2,
    note: null
  },
  {
    id: "m100",
    matchNumber: 100,
    stage: "Quarterfinal",
    group: null,
    round: "Quarterfinal",
    date: "2026-07-11",
    venue: "Arrowhead Stadium, Kansas City",
    home: "Argentina",
    away: "Switzerland",
    homeScore: 3,
    awayScore: 1,
    note: null
  },

  // ---------------- SEMIFINAL ----------------
  {
    id: "m101",
    matchNumber: 101,
    stage: "Semifinal",
    group: null,
    round: "Semifinal",
    date: "2026-07-14",
    venue: "AT&T Stadium, Arlington, Texas",
    home: "France",
    away: "Spain",
    homeScore: 0,
    awayScore: 2,
    note: null
  },
  {
    id: "m102",
    matchNumber: 102,
    stage: "Semifinal",
    group: null,
    round: "Semifinal",
    date: "2026-07-15",
    venue: "Mercedes-Benz Stadium, Atlanta",
    home: "England",
    away: "Argentina",
    homeScore: 1,
    awayScore: 2,
    note: null
  },

  // ---------------- THIRD PLACE ----------------
  {
    id: "m103",
    matchNumber: 103,
    stage: "Third Place",
    group: null,
    round: "Third Place Playoff",
    date: "2026-07-18",
    venue: "Hard Rock Stadium, Miami Gardens",
    home: "France",
    away: "England",
    homeScore: null,
    awayScore: null,
    note: null
  },

  // ---------------- FINAL ----------------
  {
    id: "m104",
    matchNumber: 104,
    stage: "Final",
    group: null,
    round: "Final",
    date: "2026-07-19",
    venue: "MetLife Stadium, East Rutherford, New Jersey",
    home: "Spain",
    away: "Argentina",
    homeScore: null,
    awayScore: null,
    note: null
  }
];
