// ============================================================
// FIFA WORLD CUP 2026 -- MATCH DATA
// ============================================================
// This is the ONLY file you need to edit to keep things current.
//
// Each match is one object. Fields you will actually touch:
//   home / away       -- team names (e.g. 'Argentina')
//   homeScore / awayScore -- final score as numbers, or null if not played yet
//   date               -- 'YYYY-MM-DD'
//   venue              -- stadium / city
//   watched            -- leave this alone, the app manages it via localStorage
//
// Do NOT change 'id' once you have started checking off matches --
// it is the key used to remember what you have watched.
// ============================================================

const WORLD_CUP_MATCHES = [

  // ---------------- GROUP STAGE ----------------
  // Group A
  {
    id: "ga-1",
    matchNumber: 1,
    stage: "Group Stage",
    group: "Group A",
    round: "Matchday 1",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "A1",
    away: "A2",
    homeScore: null,
    awayScore: null
  },
  {
    id: "ga-2",
    matchNumber: 2,
    stage: "Group Stage",
    group: "Group A",
    round: "Matchday 1",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "A3",
    away: "A4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "ga-3",
    matchNumber: 3,
    stage: "Group Stage",
    group: "Group A",
    round: "Matchday 2",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "A1",
    away: "A3",
    homeScore: null,
    awayScore: null
  },
  {
    id: "ga-4",
    matchNumber: 4,
    stage: "Group Stage",
    group: "Group A",
    round: "Matchday 2",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "A2",
    away: "A4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "ga-5",
    matchNumber: 5,
    stage: "Group Stage",
    group: "Group A",
    round: "Matchday 3",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "A1",
    away: "A4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "ga-6",
    matchNumber: 6,
    stage: "Group Stage",
    group: "Group A",
    round: "Matchday 3",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "A2",
    away: "A3",
    homeScore: null,
    awayScore: null
  },
  // Group B
  {
    id: "gb-7",
    matchNumber: 7,
    stage: "Group Stage",
    group: "Group B",
    round: "Matchday 1",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "B1",
    away: "B2",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gb-8",
    matchNumber: 8,
    stage: "Group Stage",
    group: "Group B",
    round: "Matchday 1",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "B3",
    away: "B4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gb-9",
    matchNumber: 9,
    stage: "Group Stage",
    group: "Group B",
    round: "Matchday 2",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "B1",
    away: "B3",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gb-10",
    matchNumber: 10,
    stage: "Group Stage",
    group: "Group B",
    round: "Matchday 2",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "B2",
    away: "B4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gb-11",
    matchNumber: 11,
    stage: "Group Stage",
    group: "Group B",
    round: "Matchday 3",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "B1",
    away: "B4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gb-12",
    matchNumber: 12,
    stage: "Group Stage",
    group: "Group B",
    round: "Matchday 3",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "B2",
    away: "B3",
    homeScore: null,
    awayScore: null
  },
  // Group C
  {
    id: "gc-13",
    matchNumber: 13,
    stage: "Group Stage",
    group: "Group C",
    round: "Matchday 1",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "C1",
    away: "C2",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gc-14",
    matchNumber: 14,
    stage: "Group Stage",
    group: "Group C",
    round: "Matchday 1",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "C3",
    away: "C4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gc-15",
    matchNumber: 15,
    stage: "Group Stage",
    group: "Group C",
    round: "Matchday 2",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "C1",
    away: "C3",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gc-16",
    matchNumber: 16,
    stage: "Group Stage",
    group: "Group C",
    round: "Matchday 2",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "C2",
    away: "C4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gc-17",
    matchNumber: 17,
    stage: "Group Stage",
    group: "Group C",
    round: "Matchday 3",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "C1",
    away: "C4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gc-18",
    matchNumber: 18,
    stage: "Group Stage",
    group: "Group C",
    round: "Matchday 3",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "C2",
    away: "C3",
    homeScore: null,
    awayScore: null
  },
  // Group D
  {
    id: "gd-19",
    matchNumber: 19,
    stage: "Group Stage",
    group: "Group D",
    round: "Matchday 1",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "D1",
    away: "D2",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gd-20",
    matchNumber: 20,
    stage: "Group Stage",
    group: "Group D",
    round: "Matchday 1",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "D3",
    away: "D4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gd-21",
    matchNumber: 21,
    stage: "Group Stage",
    group: "Group D",
    round: "Matchday 2",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "D1",
    away: "D3",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gd-22",
    matchNumber: 22,
    stage: "Group Stage",
    group: "Group D",
    round: "Matchday 2",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "D2",
    away: "D4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gd-23",
    matchNumber: 23,
    stage: "Group Stage",
    group: "Group D",
    round: "Matchday 3",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "D1",
    away: "D4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gd-24",
    matchNumber: 24,
    stage: "Group Stage",
    group: "Group D",
    round: "Matchday 3",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "D2",
    away: "D3",
    homeScore: null,
    awayScore: null
  },
  // Group E
  {
    id: "ge-25",
    matchNumber: 25,
    stage: "Group Stage",
    group: "Group E",
    round: "Matchday 1",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "E1",
    away: "E2",
    homeScore: null,
    awayScore: null
  },
  {
    id: "ge-26",
    matchNumber: 26,
    stage: "Group Stage",
    group: "Group E",
    round: "Matchday 1",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "E3",
    away: "E4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "ge-27",
    matchNumber: 27,
    stage: "Group Stage",
    group: "Group E",
    round: "Matchday 2",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "E1",
    away: "E3",
    homeScore: null,
    awayScore: null
  },
  {
    id: "ge-28",
    matchNumber: 28,
    stage: "Group Stage",
    group: "Group E",
    round: "Matchday 2",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "E2",
    away: "E4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "ge-29",
    matchNumber: 29,
    stage: "Group Stage",
    group: "Group E",
    round: "Matchday 3",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "E1",
    away: "E4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "ge-30",
    matchNumber: 30,
    stage: "Group Stage",
    group: "Group E",
    round: "Matchday 3",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "E2",
    away: "E3",
    homeScore: null,
    awayScore: null
  },
  // Group F
  {
    id: "gf-31",
    matchNumber: 31,
    stage: "Group Stage",
    group: "Group F",
    round: "Matchday 1",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "F1",
    away: "F2",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gf-32",
    matchNumber: 32,
    stage: "Group Stage",
    group: "Group F",
    round: "Matchday 1",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "F3",
    away: "F4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gf-33",
    matchNumber: 33,
    stage: "Group Stage",
    group: "Group F",
    round: "Matchday 2",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "F1",
    away: "F3",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gf-34",
    matchNumber: 34,
    stage: "Group Stage",
    group: "Group F",
    round: "Matchday 2",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "F2",
    away: "F4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gf-35",
    matchNumber: 35,
    stage: "Group Stage",
    group: "Group F",
    round: "Matchday 3",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "F1",
    away: "F4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gf-36",
    matchNumber: 36,
    stage: "Group Stage",
    group: "Group F",
    round: "Matchday 3",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "F2",
    away: "F3",
    homeScore: null,
    awayScore: null
  },
  // Group G
  {
    id: "gg-37",
    matchNumber: 37,
    stage: "Group Stage",
    group: "Group G",
    round: "Matchday 1",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "G1",
    away: "G2",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gg-38",
    matchNumber: 38,
    stage: "Group Stage",
    group: "Group G",
    round: "Matchday 1",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "G3",
    away: "G4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gg-39",
    matchNumber: 39,
    stage: "Group Stage",
    group: "Group G",
    round: "Matchday 2",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "G1",
    away: "G3",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gg-40",
    matchNumber: 40,
    stage: "Group Stage",
    group: "Group G",
    round: "Matchday 2",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "G2",
    away: "G4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gg-41",
    matchNumber: 41,
    stage: "Group Stage",
    group: "Group G",
    round: "Matchday 3",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "G1",
    away: "G4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gg-42",
    matchNumber: 42,
    stage: "Group Stage",
    group: "Group G",
    round: "Matchday 3",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "G2",
    away: "G3",
    homeScore: null,
    awayScore: null
  },
  // Group H
  {
    id: "gh-43",
    matchNumber: 43,
    stage: "Group Stage",
    group: "Group H",
    round: "Matchday 1",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "H1",
    away: "H2",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gh-44",
    matchNumber: 44,
    stage: "Group Stage",
    group: "Group H",
    round: "Matchday 1",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "H3",
    away: "H4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gh-45",
    matchNumber: 45,
    stage: "Group Stage",
    group: "Group H",
    round: "Matchday 2",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "H1",
    away: "H3",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gh-46",
    matchNumber: 46,
    stage: "Group Stage",
    group: "Group H",
    round: "Matchday 2",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "H2",
    away: "H4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gh-47",
    matchNumber: 47,
    stage: "Group Stage",
    group: "Group H",
    round: "Matchday 3",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "H1",
    away: "H4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gh-48",
    matchNumber: 48,
    stage: "Group Stage",
    group: "Group H",
    round: "Matchday 3",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "H2",
    away: "H3",
    homeScore: null,
    awayScore: null
  },
  // Group I
  {
    id: "gi-49",
    matchNumber: 49,
    stage: "Group Stage",
    group: "Group I",
    round: "Matchday 1",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "I1",
    away: "I2",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gi-50",
    matchNumber: 50,
    stage: "Group Stage",
    group: "Group I",
    round: "Matchday 1",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "I3",
    away: "I4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gi-51",
    matchNumber: 51,
    stage: "Group Stage",
    group: "Group I",
    round: "Matchday 2",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "I1",
    away: "I3",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gi-52",
    matchNumber: 52,
    stage: "Group Stage",
    group: "Group I",
    round: "Matchday 2",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "I2",
    away: "I4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gi-53",
    matchNumber: 53,
    stage: "Group Stage",
    group: "Group I",
    round: "Matchday 3",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "I1",
    away: "I4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gi-54",
    matchNumber: 54,
    stage: "Group Stage",
    group: "Group I",
    round: "Matchday 3",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "I2",
    away: "I3",
    homeScore: null,
    awayScore: null
  },
  // Group J
  {
    id: "gj-55",
    matchNumber: 55,
    stage: "Group Stage",
    group: "Group J",
    round: "Matchday 1",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "J1",
    away: "J2",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gj-56",
    matchNumber: 56,
    stage: "Group Stage",
    group: "Group J",
    round: "Matchday 1",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "J3",
    away: "J4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gj-57",
    matchNumber: 57,
    stage: "Group Stage",
    group: "Group J",
    round: "Matchday 2",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "J1",
    away: "J3",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gj-58",
    matchNumber: 58,
    stage: "Group Stage",
    group: "Group J",
    round: "Matchday 2",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "J2",
    away: "J4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gj-59",
    matchNumber: 59,
    stage: "Group Stage",
    group: "Group J",
    round: "Matchday 3",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "J1",
    away: "J4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gj-60",
    matchNumber: 60,
    stage: "Group Stage",
    group: "Group J",
    round: "Matchday 3",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "J2",
    away: "J3",
    homeScore: null,
    awayScore: null
  },
  // Group K
  {
    id: "gk-61",
    matchNumber: 61,
    stage: "Group Stage",
    group: "Group K",
    round: "Matchday 1",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "K1",
    away: "K2",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gk-62",
    matchNumber: 62,
    stage: "Group Stage",
    group: "Group K",
    round: "Matchday 1",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "K3",
    away: "K4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gk-63",
    matchNumber: 63,
    stage: "Group Stage",
    group: "Group K",
    round: "Matchday 2",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "K1",
    away: "K3",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gk-64",
    matchNumber: 64,
    stage: "Group Stage",
    group: "Group K",
    round: "Matchday 2",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "K2",
    away: "K4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gk-65",
    matchNumber: 65,
    stage: "Group Stage",
    group: "Group K",
    round: "Matchday 3",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "K1",
    away: "K4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gk-66",
    matchNumber: 66,
    stage: "Group Stage",
    group: "Group K",
    round: "Matchday 3",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "K2",
    away: "K3",
    homeScore: null,
    awayScore: null
  },
  // Group L
  {
    id: "gl-67",
    matchNumber: 67,
    stage: "Group Stage",
    group: "Group L",
    round: "Matchday 1",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "L1",
    away: "L2",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gl-68",
    matchNumber: 68,
    stage: "Group Stage",
    group: "Group L",
    round: "Matchday 1",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "L3",
    away: "L4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gl-69",
    matchNumber: 69,
    stage: "Group Stage",
    group: "Group L",
    round: "Matchday 2",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "L1",
    away: "L3",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gl-70",
    matchNumber: 70,
    stage: "Group Stage",
    group: "Group L",
    round: "Matchday 2",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "L2",
    away: "L4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gl-71",
    matchNumber: 71,
    stage: "Group Stage",
    group: "Group L",
    round: "Matchday 3",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "L1",
    away: "L4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "gl-72",
    matchNumber: 72,
    stage: "Group Stage",
    group: "Group L",
    round: "Matchday 3",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "L2",
    away: "L3",
    homeScore: null,
    awayScore: null
  },

  // ---------------- ROUND OF 32 ----------------
  {
    id: "r32-73",
    matchNumber: 73,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "R32 Team 1",
    away: "R32 Team 2",
    homeScore: null,
    awayScore: null
  },
  {
    id: "r32-74",
    matchNumber: 74,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "R32 Team 3",
    away: "R32 Team 4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "r32-75",
    matchNumber: 75,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "R32 Team 5",
    away: "R32 Team 6",
    homeScore: null,
    awayScore: null
  },
  {
    id: "r32-76",
    matchNumber: 76,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "R32 Team 7",
    away: "R32 Team 8",
    homeScore: null,
    awayScore: null
  },
  {
    id: "r32-77",
    matchNumber: 77,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "R32 Team 9",
    away: "R32 Team 10",
    homeScore: null,
    awayScore: null
  },
  {
    id: "r32-78",
    matchNumber: 78,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "R32 Team 11",
    away: "R32 Team 12",
    homeScore: null,
    awayScore: null
  },
  {
    id: "r32-79",
    matchNumber: 79,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "R32 Team 13",
    away: "R32 Team 14",
    homeScore: null,
    awayScore: null
  },
  {
    id: "r32-80",
    matchNumber: 80,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "R32 Team 15",
    away: "R32 Team 16",
    homeScore: null,
    awayScore: null
  },
  {
    id: "r32-81",
    matchNumber: 81,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "R32 Team 17",
    away: "R32 Team 18",
    homeScore: null,
    awayScore: null
  },
  {
    id: "r32-82",
    matchNumber: 82,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "R32 Team 19",
    away: "R32 Team 20",
    homeScore: null,
    awayScore: null
  },
  {
    id: "r32-83",
    matchNumber: 83,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "R32 Team 21",
    away: "R32 Team 22",
    homeScore: null,
    awayScore: null
  },
  {
    id: "r32-84",
    matchNumber: 84,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "R32 Team 23",
    away: "R32 Team 24",
    homeScore: null,
    awayScore: null
  },
  {
    id: "r32-85",
    matchNumber: 85,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "R32 Team 25",
    away: "R32 Team 26",
    homeScore: null,
    awayScore: null
  },
  {
    id: "r32-86",
    matchNumber: 86,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "R32 Team 27",
    away: "R32 Team 28",
    homeScore: null,
    awayScore: null
  },
  {
    id: "r32-87",
    matchNumber: 87,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "R32 Team 29",
    away: "R32 Team 30",
    homeScore: null,
    awayScore: null
  },
  {
    id: "r32-88",
    matchNumber: 88,
    stage: "Round of 32",
    group: null,
    round: "Round of 32",
    date: "2026-06-00",
    venue: "Venue TBD",
    home: "R32 Team 31",
    away: "R32 Team 32",
    homeScore: null,
    awayScore: null
  },

  // ---------------- ROUND OF 16 ----------------
  {
    id: "r16-89",
    matchNumber: 89,
    stage: "Round of 16",
    group: null,
    round: "Round of 16",
    date: "2026-07-00",
    venue: "Venue TBD",
    home: "R16 Team 1",
    away: "R16 Team 2",
    homeScore: null,
    awayScore: null
  },
  {
    id: "r16-90",
    matchNumber: 90,
    stage: "Round of 16",
    group: null,
    round: "Round of 16",
    date: "2026-07-00",
    venue: "Venue TBD",
    home: "R16 Team 3",
    away: "R16 Team 4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "r16-91",
    matchNumber: 91,
    stage: "Round of 16",
    group: null,
    round: "Round of 16",
    date: "2026-07-00",
    venue: "Venue TBD",
    home: "R16 Team 5",
    away: "R16 Team 6",
    homeScore: null,
    awayScore: null
  },
  {
    id: "r16-92",
    matchNumber: 92,
    stage: "Round of 16",
    group: null,
    round: "Round of 16",
    date: "2026-07-00",
    venue: "Venue TBD",
    home: "R16 Team 7",
    away: "R16 Team 8",
    homeScore: null,
    awayScore: null
  },
  {
    id: "r16-93",
    matchNumber: 93,
    stage: "Round of 16",
    group: null,
    round: "Round of 16",
    date: "2026-07-00",
    venue: "Venue TBD",
    home: "R16 Team 9",
    away: "R16 Team 10",
    homeScore: null,
    awayScore: null
  },
  {
    id: "r16-94",
    matchNumber: 94,
    stage: "Round of 16",
    group: null,
    round: "Round of 16",
    date: "2026-07-00",
    venue: "Venue TBD",
    home: "R16 Team 11",
    away: "R16 Team 12",
    homeScore: null,
    awayScore: null
  },
  {
    id: "r16-95",
    matchNumber: 95,
    stage: "Round of 16",
    group: null,
    round: "Round of 16",
    date: "2026-07-00",
    venue: "Venue TBD",
    home: "R16 Team 13",
    away: "R16 Team 14",
    homeScore: null,
    awayScore: null
  },
  {
    id: "r16-96",
    matchNumber: 96,
    stage: "Round of 16",
    group: null,
    round: "Round of 16",
    date: "2026-07-00",
    venue: "Venue TBD",
    home: "R16 Team 15",
    away: "R16 Team 16",
    homeScore: null,
    awayScore: null
  },

  // ---------------- QUARTERFINAL ----------------
  {
    id: "qf-97",
    matchNumber: 97,
    stage: "Quarterfinal",
    group: null,
    round: "Quarterfinal",
    date: "2026-07-00",
    venue: "Venue TBD",
    home: "QF Team 1",
    away: "QF Team 2",
    homeScore: null,
    awayScore: null
  },
  {
    id: "qf-98",
    matchNumber: 98,
    stage: "Quarterfinal",
    group: null,
    round: "Quarterfinal",
    date: "2026-07-00",
    venue: "Venue TBD",
    home: "QF Team 3",
    away: "QF Team 4",
    homeScore: null,
    awayScore: null
  },
  {
    id: "qf-99",
    matchNumber: 99,
    stage: "Quarterfinal",
    group: null,
    round: "Quarterfinal",
    date: "2026-07-00",
    venue: "Venue TBD",
    home: "QF Team 5",
    away: "QF Team 6",
    homeScore: null,
    awayScore: null
  },
  {
    id: "qf-100",
    matchNumber: 100,
    stage: "Quarterfinal",
    group: null,
    round: "Quarterfinal",
    date: "2026-07-00",
    venue: "Venue TBD",
    home: "QF Team 7",
    away: "QF Team 8",
    homeScore: null,
    awayScore: null
  },

  // ---------------- SEMIFINAL ----------------
  {
    id: "sf-101",
    matchNumber: 101,
    stage: "Semifinal",
    group: null,
    round: "Semifinal",
    date: "2026-07-00",
    venue: "Venue TBD",
    home: "SF Team 1",
    away: "SF Team 2",
    homeScore: null,
    awayScore: null
  },
  {
    id: "sf-102",
    matchNumber: 102,
    stage: "Semifinal",
    group: null,
    round: "Semifinal",
    date: "2026-07-00",
    venue: "Venue TBD",
    home: "SF Team 3",
    away: "SF Team 4",
    homeScore: null,
    awayScore: null
  },

  // ---------------- THIRD PLACE ----------------
  {
    id: "third-103",
    matchNumber: 103,
    stage: "Third Place",
    group: null,
    round: "Third Place Playoff",
    date: "2026-07-18",
    venue: "Venue TBD",
    home: "SF Loser 1",
    away: "SF Loser 2",
    homeScore: null,
    awayScore: null
  },

  // ---------------- FINAL ----------------
  {
    id: "final-104",
    matchNumber: 104,
    stage: "Final",
    group: null,
    round: "Final",
    date: "2026-07-19",
    venue: "Venue TBD (MetLife Stadium, New Jersey)",
    home: "SF Winner 1",
    away: "SF Winner 2",
    homeScore: null,
    awayScore: null
  }
];
